// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Rx7qJcw0_jWH0p5rVP6mfNmCjjWIClY',
    appId: '1:1051040199369:web:31bee951b6dd536bb35318',
    messagingSenderId: '1051040199369',
    projectId: 'yemenbus-2c9e3',
    authDomain: 'yemenbus-2c9e3.firebaseapp.com',
    storageBucket: 'yemenbus-2c9e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Rx7qJcw0_jWH0p5rVP6mfNmCjjWIClY',
    appId: '1:1051040199369:android:31bee951b6dd536bb35318',
    messagingSenderId: '1051040199369',
    projectId: 'yemenbus-2c9e3',
    storageBucket: 'yemenbus-2c9e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Rx7qJcw0_jWH0p5rVP6mfNmCjjWIClY',
    appId: '1:1051040199369:ios:31bee951b6dd536bb35318',
    messagingSenderId: '1051040199369',
    projectId: 'yemenbus-2c9e3',
    storageBucket: 'yemenbus-2c9e3.firebasestorage.app',
    iosBundleId: 'com.hashem.yemenbus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Rx7qJcw0_jWH0p5rVP6mfNmCjjWIClY',
    appId: '1:1051040199369:ios:31bee951b6dd536bb35318',
    messagingSenderId: '1051040199369',
    projectId: 'yemenbus-2c9e3',
    storageBucket: 'yemenbus-2c9e3.firebasestorage.app',
    iosBundleId: 'com.hashem.yemenbus',
  );
} 